name: fitness
description: "Project for SWE460 Course"
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive:
  hive_flutter:
  connectivity_plus:
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  firebase_storage: ^11.6.6 
  cloud_firestore: ^4.15.5
  easy_localization: 
  easy_logger:
  ##ui
  persistent_bottom_nav_bar_v2: ^4.2.8
  icons_plus: 
  phone_form_field:
  pinput:  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator:
  build_runner:


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/locales/