class Texts {
  static const String fitnessapp = 'Fitness App';
  static const String login = 'Log In';
  static const String logout = 'Log Out';
  static const String register = 'Register';
  static const String profile = 'Profile';
  static const String exercise = 'Exercise';
  static const String calorie = 'Calorie';
  static const String phoneNumber = 'Phone Number';
  static const String phoneNumberAlert = 'Phone Number is Invalid';
  static const String someThingWentWrong = 'Something Went Wrong';
  static const String tryAgain = 'Try Again';
  static const String loginTitle = 'Catch Your Dream Form';
  static const String name = 'Name';
  static const String surname = 'Surname';
  static const String weight = 'Weight';
  static const String height = 'Height';
  static const String gender = 'Gender';
  static const String birthDate = 'Birthdate';
  static const String male = 'Male';
  static const String female = 'Female';
  static const String ok = 'OK';
  static const String cancel = 'Cancel';
  static const String taptochange = 'Tap to Change';
  static const String edit = 'Edit';
  static const String update = 'Update';
  static const String equipments = 'Equipments';
  static const String muscles = 'Muscles';
  static const String reset = 'Reset';
  static const String apply = 'Apply';
  static const String help = 'Help';
  static const String add = 'Add To List';
  static const String calorieTitle = 'Your Daily Calorie Tracking';
  static const String calorieHint = '140 grams rice, 3 tomatoes...';
  static const String calorieHelp =
      'A string containing food or drink items. If you wish to calculate a specific quantity, you may prefix a quantity before an item. For example, 3 tomatoes or 1lb beef brisket. If no quantity is specified, the default quantity is 100 grams. Queries cannot exceed 1500 characters.';
  static const String bmr = 'Basal Metabolic Rate';
  static const String bmi = 'Body Mass Index';
}
